### ISSUE TITLE
Adding dark mode

### ISSUE THREAD

**Issue by sreeram-venkitesh** [AbhayVAshokan/Hack-NASA-using-HTML#12]
@AbhayVAshokan I like to take this up

**Comment by AbhayVAshokan** [comment]
That would be great!

**Comment by AbhayVAshokan** [comment]
@sreeram-venkitesh while editing `style.css` remove [lines 91-92](https://github.com/AbhayVAshokan/Hack-NASA-using-HTML/blob/main/src/style.css#L91-L92). It isn't necessary since it is already cascaded from `.card` class.

**Comment by AbhayVAshokan** [comment]
Closed #12 via #13
